### ISSUE TITLE
Allow individual custom shares in percentage for the voters

### ISSUE THREAD

**Issue by Highjhacker** [ark-collective/core-payroll#26]
It would be great to be able to specify custom shares for the voters like this ;

{
"voter1": 65,
"voter2": 74,
...
}

Or

fixed: [{ address: bla, amount: 10, type: 'percentage' }]

**Comment by faustbrian** [comment]
Implemented in https://github.com/ark-collective/core-payroll/commit/f946aa3fc399d6fa1f25b87f8193a3e216269928. Will let it sit on the develop branch for a bit to test it.
